# .github/workflows/tests.yml
# Lance pytest automatiquement à chaque push ou pull request

name: Tests Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v4

      - name: 🐍 Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Installation des dépendances
        run: pip install -r requirements.txt

      - name: 🧪 Lancement des tests pytest
        run: pytest tests/ -v